app.run(function(FIREBASE_CONFIG){
	firebase.initializeApp(FIREBASE_CONFIG);
	console.log("intializing the firebase");
});

app.config(function($routeProvider){
	$routeProvider
	.when('/songs/list',{
		templateUrl:'/partials/mh-list.html',
		controller:'mhListCtrl'
	})
	.when('/songs/Profile',{
		templateUrl:'/partials/mh-profile.html',
		controller:"mhViewProfile"
	})
	.when('/songs/edit/:id',{
        templateUrl:'partials/mh-newSong.html',
        controller:'mhEditCtrl'
    }) 
    .when('/songs/view/:id',{
        templateUrl:'partials/mh-view.html',
        controller:'mhViewCtrl',
    })    
	.when('/songs/new',{
		templateUrl:'/partials/mh-newSong.html',
		controller:"mhNewSongCtrl"
	})
	.otherwise('/songs/list');
});